// <auto-generated />
using EfCore6.Model.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace EfCore6.Model.Optimized
{
    [DbContext(typeof(ApplicationState))]
    partial class ApplicationStateModel : RuntimeModel
    {
        private static ApplicationStateModel? _instance;
        public static IModel Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new ApplicationStateModel();
                    _instance.Initialize();
                    _instance.Customize();
                }

                return _instance;
            }
        }

        partial void Initialize();

        partial void Customize();
    }
}
