// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace EfCore6.Model.Optimized
{
    partial class ApplicationStateModel
    {
        partial void Initialize()
        {
            var definition = DefinitionEntityType.Create(this);
            var index = IndexEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var identityRoleint = IdentityRoleintEntityType.Create(this);
            var identityRoleClaimint = IdentityRoleClaimintEntityType.Create(this);
            var identityUserClaimint = IdentityUserClaimintEntityType.Create(this);
            var identityUserLoginint = IdentityUserLoginintEntityType.Create(this);
            var identityUserRoleint = IdentityUserRoleintEntityType.Create(this);
            var identityUserTokenint = IdentityUserTokenintEntityType.Create(this);

            IndexEntityType.CreateForeignKey1(index, user);
            UserEntityType.CreateForeignKey1(user, definition);
            IdentityRoleClaimintEntityType.CreateForeignKey1(identityRoleClaimint, identityRoleint);
            IdentityUserClaimintEntityType.CreateForeignKey1(identityUserClaimint, user);
            IdentityUserLoginintEntityType.CreateForeignKey1(identityUserLoginint, user);
            IdentityUserRoleintEntityType.CreateForeignKey1(identityUserRoleint, identityRoleint);
            IdentityUserRoleintEntityType.CreateForeignKey2(identityUserRoleint, user);
            IdentityUserTokenintEntityType.CreateForeignKey1(identityUserTokenint, user);

            DefinitionEntityType.CreateAnnotations(definition);
            IndexEntityType.CreateAnnotations(index);
            UserEntityType.CreateAnnotations(user);
            IdentityRoleintEntityType.CreateAnnotations(identityRoleint);
            IdentityRoleClaimintEntityType.CreateAnnotations(identityRoleClaimint);
            IdentityUserClaimintEntityType.CreateAnnotations(identityUserClaimint);
            IdentityUserLoginintEntityType.CreateAnnotations(identityUserLoginint);
            IdentityUserRoleintEntityType.CreateAnnotations(identityUserRoleint);
            IdentityUserTokenintEntityType.CreateAnnotations(identityUserTokenint);

            AddAnnotation("ProductVersion", "6.0.0-preview.7.21378.4");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
